apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"mesh":"defaultConfig:\n  discoveryAddress:
      istiod.istio-system.svc:15012\n  proxyMetadata: {}\n  tracing:\n   
      zipkin:\n      address: zipkin.istio-system:9411\nenablePrometheusMerge:
      true\nextensionProviders:\n- envoyExtAuthzHttp:\n   
      headersToDownstreamOnDeny:\n    - content-type\n    - set-cookie\n   
      headersToUpstreamOnAllow:\n    - x-forwarded-access-token\n    -
      authorization\n    - path\n    - x-auth-request-user\n    -
      x-auth-request-email\n    - x-auth-request-access-token\n   
      includeHeadersInCheck:\n    - authorization\n    - cookie\n    port: 443\n   
      service: oauth2-proxy.oauth2-proxy.svc.cluster.local\n    timeout: 1.5s\n 
      name: oauth2-proxy\nrootNamespace: istio-system\ntrustDomain:
      cluster.local","meshNetworks":"networks:
      {}"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"install.operator.istio.io/owning-resource":"unknown","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"default","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.11.4","release":"istio"},"name":"istio","namespace":"istio-system"}}
#    key: string
  creationTimestamp: '2022-03-11T20:58:04Z'
  labels:
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.11.4
    release: istio
#    key: string
  namespace: istio-system
  resourceVersion: '9761109'
  uid: ae7676ea-548e-4dcf-917e-f1b31e88a2f9
  fields:
    - istio
    - 47d
data:
  mesh: |-
    extensionProviders:
          - name: oauth2-proxy
            envoyExtAuthzHttp:
              service: oauth2-proxy.oauth2-proxy.svc.cluster.local
              port: 443
              timeout: 1.5s
              includeHeadersInCheck: ["authorization", "cookie"]
              headersToUpstreamOnAllow: ["x-forwarded-access-token", "authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token"]
              headersToDownstreamOnDeny: ["content-type", "set-cookie"]
  
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
  
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
#  key: string
__clone: true
#binaryData:
#  key: string
#immutable: boolean
